language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --dev --prefer-source --no-interaction
  - mysql -e "create database IF NOT EXISTS currencyshifts;" -uroot
  - php artisan migrate:refresh
  - php artisan rates:update

script: phpunit